# kind: ConfigMap
# apiVersion: v1
# metadata:
#  name: frontend-configmap
#  namespace: expense
# data: 
#   DB_HOST: mysql-service #mysql component service name
# #configmap details to tell frontend to connect to mysql service
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: expense
  labels:
    app: expense
    tier: web
    component: frontend
  #these labels belong to deployment set resource
spec:
  replicas: 2 #specify no. of pods, as per our requirement
  selector: #select the pods with these labels
    matchLabels:
      app: expense
      tier: web
      component: frontend
    #below mentioned code refers to pod definition
  template:
    metadata:
      labels:
        app: expense
        tier: web
        component: frontend
    spec:
      containers:
      - name: frontend
        image: nagamanimuvva/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #     name: frontend-configmap
---
#creating frontend service to connect to frontend
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: expense
    tier: web
    component: frontend
  ports:
    - protocol: TCP
      port: 80   #service port
      targetPort: 80  #pod port