apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: expense
  labels:
    app: expense
    tier: db
    component: mysql
  #these labels belong to deployment set resource
spec:
  replicas: 3 #specify no. of pods, as per our requirement
  selector: #select the pods with these labels
    matchLabels:
      app: expense
      tier: db
      component: mysql
    #below mentioned code refers to pod definition
  template:
    metadata:
      labels:
        app: expense
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: nagamanimuvva/mysql:v1.0
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  namespace: expense
spec:
  selector:
    app: expense
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306   #service port
      targetPort: 3306  #pod port